Repository wso2-extensions/identity-inbound-auth-oauth, pull requests merged in 2020-02, with the labels that each got.

#1308 Improved the scope not found error message
  components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/OAuthAdminServiceImpl.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done, Internal-Contributor

#1309 Remove unwanted deprecation and improve styling
  components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/listener/IdentityOathEventListener.java
  components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/AccessTokenDAOImpl.java
  components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/AuthorizationCodeDAO.java
  components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/AuthorizationCodeDAOImpl.java
  components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/SQLQueries.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done, Internal-Contributor

#1314 Fix for adding SameSite Cookie attribute in Opbs
  components/org.wso2.carbon.identity.oidc.session/src/main/java/org/wso2/carbon/identity/oidc/session/DefaultOIDCSessionStateManager.java
  components/org.wso2.carbon.identity.oidc.session/src/main/java/org/wso2/carbon/identity/oidc/session/util/OIDCSessionManagementUtil.java
  pom.xml
Labels: Code-Quality-Review/Done, Functionality-Review/Done

#1313 Fix issue with CON_APP_KEY recovery when JWT issuer is used
  components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/AccessTokenDAOImpl.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done
